:- consult('personaje').
:- consult('tripulacion').
:- consult('fruta').
:- consult('relaciones').
:- consult('recompensas').
:- consult('eventos').
:- consult('organizaciones').
:- consult('rango').
:- consult('reglas').